buildCommand: npm run build
publishDir: build

services:
  - type: web
    name: your-backend-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:5000 app:app
